FROM tomcat:9-jdk14-openjdk-buster

ARG war_file=target/AuScope-Portal-API-5.2.1-SNAPSHOT.war

ADD ${war_file} /usr/local/tomcat/webapps/AuScope-Portal-API.war

RUN rm -rf /usr/local/tomcat/webapps/ROOT \
  && unzip /usr/local/tomcat/webapps/AuScope-Portal-API.war -d /usr/local/tomcat/webapps/ROOT \
  && rm /usr/local/tomcat/webapps/AuScope-Portal-API.war \
  && sed 's/active: test/#active: test/' /usr/local/tomcat/webapps/ROOT/WEB-INF/classes/application.yaml.default | sed 's/#active: prod/active: prod/' > /usr/local/tomcat/webapps/ROOT/WEB-INF/classes/application.yaml
