# This file is part of the 'test' build profile and enables the server to use the test geonetwork server
auscope:
  registries:
      - id: auscopeTestRegistry
        serviceUrl: http://au-portal-2.it.csiro.au/geonetwork/srv/eng/csw
        recordInformationUrl: http://au-portal-2.it.csiro.au/geonetwork/srv/eng/catalog.search#/metadata/%1$s
        title: AuScope Test Geonetwork
        serverType: Default
