# This file is part of the 'prod' build profile and enables the server to use the production geonetwork server
auscope:
  registries:
      - id: cswAuscopeProduction
        serviceUrl: http://portal.auscope.org/geonetwork/srv/eng/csw
        recordInformationUrl: http://portal.auscope.org/geonetwork/srv/eng/catalog.search#/metadata/%1$s
        title: AuScope Geonetwork
        serverType: Default
        pageSize: 500
