# This file is part of the 'test' build profile and enables the server to use the test geonetwork server
auscope:
  registries:
      - id: auscopeTestRegistry
        serviceUrl: https://auportal-dev.geoanalytics.group/geonetwork/srv/eng/csw
        recordInformationUrl: https://auportal-dev.geoanalytics.group/geonetwork/srv/eng/catalog.search#/metadata/%1$s
        title: AuScope DevTest Geonetwork
        serverType: Default
        pageSize: 500
