csw:
   registries:
      - id: cswGAECat
        serviceUrl: https://ecat.ga.gov.au/geonetwork/srv/eng/csw
        recordInformationUrl: https://ecat.ga.gov.au/geonetwork/srv/eng/main.home?uuid=%1$s
        title: Geoscience Australia eCat
        serverType: Default
        pageSize: 400
      - id: cswNCI
        serviceUrl: https://geonetwork.nci.org.au/geonetwork/srv/eng/csw
        recordInformationUrl: "https://geonetwork.nci.org.au/geonetwork/srv/eng/catalog.search#/metadata/%1$s"
        title: NCI Data Portal
        serverType: Default
        pageSize: 500
      # - id: Grace
      #   serviceUrl: https://insargrace.geoanalytics.csiro.au/pycsw/api
      #   recordInformationUrl: "https://insargrace.geoanalytics.csiro.au/pycsw/api/catalog.search#/metadata/%1$s"
      #   title: InSAR/GRACE
      #   serverType: PyCSW
      #   pageSize: 500
