apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "auscope-portal-api.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
data:
  {{ $defaultvals := .Files.Get "application.yaml.default" | fromYaml }}
  application.yaml: |-
{{ merge dict .Values.applicationconfig $defaultvals | toYaml | indent 4 }}