apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "auscope-portal-api.fullname" . }}
  labels:
    {{- include "auscope-portal-api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "auscope-portal-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "auscope-portal-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "auscope-portal-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - name: "{{ include "auscope-portal-api.fullname" . }}-config"
            mountPath: "/workspace/config/application.yaml"
            subPath: "application.yaml"
            readOnly: true
          {{- if .Values.persistence.cswcacheDir.enabled }}
          - name: cswcache
            mountPath: {{ .Values.persistence.cswcacheDir.mountPath }}
            subPath: {{ .Values.persistence.cswcacheDir.subPath }}
            readOnly: false
          {{- end }}
          {{- if .Values.existingLayerConfigMap }}
          - name: "{{ .Values.existingLayerConfigMap }}"
            mountPath: "/usr/local/tomcat/webapps/api/WEB-INF/classes/layers.yaml"
            subPath: "{{ .Values.existingLayerConfigMapKey }}"
            readOnly: true
          {{- end }}
          {{- if .Values.existingRegistriesConfigMap }}
          - name: "{{ .Values.existingRegistriesConfigMap }}"
            mountPath: "/workspace/config/application-registries.yaml"
            subPath: "{{ .Values.existingRegistriesConfigMapKey }}"
            readOnly: true
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/actuator/health/liveness
              port: http
            initialDelaySeconds: 300
            timeoutSeconds: 5
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /api/actuator/health/readiness
              port: http
            initialDelaySeconds: 300
            timeoutSeconds: 5
            periodSeconds: 60
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- with .Values.extraPodEnv }}
            {{- tpl . $ | nindent 12 }}
            {{- end }}
      volumes:
      - name: {{ include "auscope-portal-api.fullname" . }}-config
        configMap:
          name: {{ include "auscope-portal-api.fullname" . }}-config
      {{- if .Values.persistence.cswcacheDir.enabled }}
      - name: cswcache
        persistentVolumeClaim:
          claimName: {{ template "auscope-portal-api.fullname" . }}-cswcache-dir
      {{- else if not .Values.persistence.cswcacheDir.enabled }}
      - name: cswcache
        emptyDir: {}
      {{- end }}
      {{- if .Values.existingLayerConfigMap }}
      - name: {{ .Values.existingLayerConfigMap }}
        configMap:
          name: {{ .Values.existingLayerConfigMap }}
      {{- end }}
      {{- if .Values.existingRegistriesConfigMap }}
      - name: {{ .Values.existingRegistriesConfigMap }}
        configMap:
          name: {{ .Values.existingRegistriesConfigMap }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
