/*
 * This file is part of the AuScope Virtual Exploration Geophysics Lab (VEGL) project.
 * Copyright (c) 2011 CSIRO Earth Science and Resource Engineering
 *
 * Licensed under the terms of the GNU Lesser General Public License.
 */
Ext.define('ScriptBuilder.components.DefineMainFunc', {
    extend : 'ScriptBuilder.components.BasePythonComponent',

    constructor: function(config) {
        Ext.apply(config, {
            bodyStyle: "padding:5px;",
            labelWidth: 150,
            defaults: { anchor: "100%" },
            items: [{
                xtype: "textfield",
                name: "funcName",
                value: "main",
                fieldLabel: "Main Function Name",
                allowBlank: false
            }]
        });

        this.callParent(arguments);
    },

    getScript : function() {
        var text = '';

        text += "# autogenerated main definition" + this._newLine;
        text += "if __name__ == \"__main__\":" + this._newLine;
        text += this._tab + this.getValues().funcName + "()" + this._newLine;
        text += this._newLine;

        return text;
    }
});
