/*
 * This file is part of the AuScope Virtual Exploration Geophysics Lab (VEGL) project.
 * Copyright (c) 2011 CSIRO Earth Science and Resource Engineering
 *
 * Licensed under the terms of the GNU Lesser General Public License.
 */
Ext.namespace("ScriptBuilder");
Ext.ux.ComponentLoader.load( {url : ScriptBuilder.componentPath + "DefineMainFunc.json"});

DefineMainFuncNode = Ext.extend(ScriptBuilder.BasePythonComponent, {

    constructor : function(container) {
        DefineMainFuncNode.superclass.constructor.apply(this, [ container,
                "Define Main Python Function", "DefineMainFuncFunc", "s" ]);

        var numShells = container.getShellCommands().length;
        this.values.uniqueName = "DefineMainFunc" + numShells;
    },

    getScript : function() {
        var text = '';

        text += "# autogenerated main definition" + this._newLine;
        text += "if __name__ == \"__main__\":" + this._newLine;
        text += this._tab + this.values.funcName + "()" + this._newLine;
        text += this._newLine;

        return text;
    }
});
