/*
 * This file is part of the AuScope Virtual Exploration Geophysics Lab (VEGL) project.
 * Copyright (c) 2011 CSIRO Earth Science and Resource Engineering
 *
 * Licensed under the terms of the GNU Lesser General Public License.
 */
Ext.namespace("ScriptBuilder");
Ext.ux.ComponentLoader.load( {url : ScriptBuilder.componentPath + "DefinePythonFunc.json"});

DefinePythonFuncNode = Ext.extend(ScriptBuilder.BasePythonComponent, {

    constructor : function(container) {
        DefinePythonFuncNode.superclass.constructor.apply(this, [ container,
                "Define Python Function", "DefinePythonFunc", "s" ]);

        var numShells = container.getShellCommands().length;
        this.values.uniqueName = "DefinePythonFunc" + numShells;
    },

    /**
     * We generate a static def main() function
     */
    getScript : function() {
        var text = '';

        text += "# autogenerated function definition" + this._newLine;
        text += "def " + this.values.funcName + "():" + this._newLine;

        return text;
    }
});
