/*
 * This file is part of the AuScope Virtual Exploration Geophysics Lab (VEGL) project.
 * Copyright (c) 2011 CSIRO Earth Science and Resource Engineering
 *
 * Licensed under the terms of the GNU Lesser General Public License.
 */
Ext.namespace("ScriptBuilder");
Ext.ux.ComponentLoader.load( {url : ScriptBuilder.componentPath + "VEGLJobObject.json"});

VEGLJobObjectNode = Ext.extend(ScriptBuilder.BasePythonComponent, {

    constructor : function(container) {
        VEGLJobObjectNode.superclass.constructor.apply(this, [ container,
                "VEGL Job Object", "VEGLJobObject", "s" ]);

        var numShells = container.getShellCommands().length;
        this.values.uniqueName = "shell" + numShells;
    },
    
    /**
     * This is where we dynamically generate a python Getter/Setter class from the job object that
     * is sent to us 
     */
    getScript : function() {
        var classText = '';
        
        classText += '# Autogenerated Python Getter/Setter class' + this._newLine;
        classText += 'class VEGLParameters:' + this._newLine;
        
        //Iterate our fields generating getter methods
        for (var field in this.values) {
            var value = this.values[field];
            if (Ext.isFunction(value)) {
                
            } else if (Ext.isObject(value)) {
                //Ignore complex fields for the moment
            } else if (Ext.isPrimitive(value)) {
                //Primitive fields turn into 'Getters'
                classText += this._getPrimitiveFunction(field, value, this._tab);
            }
        }
        
        classText += '# Global parameter instance for reference' + this._newLine;
        classText += 'VEGLParams = VEGLParameters()' + this._newLine;
        
        classText += this._newLine;
        
        return classText;
    }
});
