# Workflow that is manually triggered - to generate coverage in the file jacaco.csv. 
# This file is then parsed to generate a coverage percentage.
# readme.MD is then updated with this value to make a coverage badge.

name: Coverage portal-core

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# runs tests and generate Jacoco report
# 
  
jobs:
  # This workflow contains a single job called "coverage"
  coverage:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Start step"
      - uses: actions/checkout@v2
      - name: Set up JDK 1.17
        uses: actions/setup-java@v1
        with:
          java-version: 1.17
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Checkout portal-core
        uses: actions/checkout@v2.3.4
        with:
          repository: chrisvpeters/portal-core
          ref: master
          path: portal-core
      - run: echo "maven step"
      - name: run tests with Maven
        run: |
          cd portal-core
          mvn test --file pom.xml
      - name: Run coverage parse script
        run: |
         chmod +x scripts/coverage_percentage_git.sh
         percent=`scripts/coverage_percentage_git.sh`
         echo $percent > coverage/percentage.txt
         echo coverage = $percent
         cat /home/runner/work/AuScope-Portal-API/AuScope-Portal-API/target/site/jacoco/jacoco.csv > coverage/jacoco.csv
        shell: bash
      - run: echo "End step"
