# This is a basic workflow that is manually triggered

name: Test workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# runs tests and generate Jacoco report
# 

env:
  # Auscope-Portal-API docker image name
  IMAGE_NAME: auscope-portal-api

jobs:
  # This workflow contains a single job called "test"
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.17
        uses: actions/setup-java@v1
        with:
          java-version: 1.17
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Checkout portal-core
        uses: actions/checkout@v2.3.4
        with:
          repository: AuScope/portal-core
          ref: master
          path: portal-core
      - name: Build portal-core 
        run: |
          cd portal-core
          mvn clean install
      - name: run tests with Maven
        run: |
          mvn test --file pom.xml
