# This is a basic workflow that is manually triggered

name: Test workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# runs tests and generate Jacoco report
# 

jobs:
  # This workflow contains a single job called "test"
  test:
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "Start step"
      - uses: actions/checkout@v2
      - name: Set up JDK 1.17
        uses: actions/setup-java@v1
        with:
          java-version: 1.17
          
      - run: |
          echo "maven step"
      - name: run tests with Maven
        run: |
          mvn test --file pom.xml
      - run: |
          echo "End step"
