CREATE TABLE users (
  id VARCHAR(128) NOT NULL,
  fullName VARCHAR(256),
  email VARCHAR(256),
  acceptedTermsConditions INTEGER,
  PRIMARY KEY (id),
  CONSTRAINT EMAIL UNIQUE (email)
);

CREATE TABLE authorities (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  authority VARCHAR(32),
  userId VARCHAR(128),
  FOREIGN KEY (userId)
    REFERENCES users(id)
    ON DELETE CASCADE
);

CREATE TABLE states (
  id VARCHAR(128) NOT NULL,
  userid VARCHAR(128),
  name VARCHAR(255),
  description VARCHAR(255),
  jsonState LONGVARCHAR NOT NULL,
  creationDate TIMESTAMP NOT NULL,
  isPublic BOOLEAN NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (userid)
    REFERENCES users(id)
    ON DELETE CASCADE
);

CREATE TABLE hashmap_params (
  key VARCHAR(128) NOT NULL,
  value LONGVARCHAR NOT NULL,
  PRIMARY KEY (key)
);

CREATE TABLE bookmarks (
  fileIdentifier VARCHAR(128) NOT NULL,
  serviceId VARCHAR(25) NOT NULL,
  userId VARCHAR(128) NOT NULL,
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  CONSTRAINT USER_ID_BOOKMARKS
    FOREIGN KEY (userId)
    REFERENCES users(id)
    ON DELETE CASCADE
);

CREATE INDEX USER_ID_BOOKMARKS ON bookmarks (userId);

CREATE TABLE bookmark_download_options (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bookmarkId INTEGER NOT NULL,
  bookmarkOptionName VARCHAR(128) NOT NULL,
  url VARCHAR(4096),
  localPath VARCHAR(1024),
  name VARCHAR(128),
  description VARCHAR(1024),
  northBoundLatitude DOUBLE,
  southBoundLatitude DOUBLE,
  eastBoundLongitude DOUBLE,
  westBoundLongitude DOUBLE,
  CONSTRAINT ID_BOOKMARKS
    FOREIGN KEY (bookmarkId)
    REFERENCES bookmarks (id)
    ON DELETE CASCADE
);

CREATE INDEX ID_BOOKMARKS ON bookmark_download_options (bookmarkId);

CREATE TABLE shorturl (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timestamp CHAR(19),
  name VARCHAR(30) NOT NULL,
  url VARCHAR(255) NOT NULL,
  persist BOOLEAN DEFAULT TRUE
);
